on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
     # matrix:
      #  node-version: [10.x, 12.x, 14.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0
        with: 
         node-version: 12.x
      - run: npm install
      - run: npm build
      - run: npm test --if-present
